In [2]:
import pandas as pd
df = pd.read_json(r'C:\Users\shres\MachineLearning\Nepse\unhpl.json')
df.head()

,businessDate,totalTrades,totalTradedQuantity,totalTradedValue,highPrice,lowPrice,closePrice
0,2026-08-10,46,4858,1821167.5,379.5,373.1,374.0
1,2026-08-07,53,7991,3008338.7,381.5,375.0,375.0
2,2026-08-06,90,23316,8867818.6,385.0,375.5,379.0
3,2026-08-05,56,9947,3769629.9,388.0,377.1,379.9
4,2026-08-04,88,21045,7997141.9,388.0,378.2,383.9

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   businessDate         224 non-null    object
 1   totalTrades          224 non-null    int64
 2   totalTradedQuantity  224 non-null    int64
 3   totalTradedValue     224 non-null    float64
 4   highPrice            224 non-null    float64
 5   lowPrice             224 non-null    float64
 6   closePrice           224 non-null    float64
dtypes: float64(4), int64(2), object(1)
memory usage: 12.4+ KB

In [4]:
df.describe()

,totalTrades,totalTradedQuantity,totalTradedValue,highPrice,lowPrice,closePrice
count,224.000000,2.240000e+02,2.240000e+02,224.000000,224.000000,224.000000
mean,490.781250,1.842857e+05,9.029447e+07,473.010670,454.797277,463.154509
std,474.738164,2.013728e+05,1.014613e+08,53.117306,49.330645,50.846291
min,33.000000,4.858000e+03,1.821168e+06,379.500000,370.000000,374.000000
25%,148.250000,3.441475e+04,1.499409e+07,415.750000,404.600000,408.837500
50%,346.500000,1.031230e+05,4.883076e+07,485.550000,468.000000,475.000000
75%,646.000000,2.568460e+05,1.321853e+08,516.025000,494.000000,502.300000
max,2710.000000,1.146555e+06,5.877639e+08,571.000000,549.000000,560.000000

In [5]:
df.isnull().sum()

businessDate           0
totalTrades            0
totalTradedQuantity    0
totalTradedValue       0
highPrice              0
lowPrice               0
closePrice             0
dtype: int64

In [6]:
df['businessDate'] = pd.to_datetime(df['businessDate'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   businessDate         224 non-null    datetime64[ns]
 1   totalTrades          224 non-null    int64
 2   totalTradedQuantity  224 non-null    int64
 3   totalTradedValue     224 non-null    float64
 4   highPrice            224 non-null    float64
 5   lowPrice             224 non-null    float64
 6   closePrice           224 non-null    float64
dtypes: datetime64[ns](1), float64(4), int64(2)
memory usage: 12.4 KB

In [8]:
df['year'] = df['businessDate'].dt.year
df['month'] = df['businessDate'].dt.month
df = df.sort_values('businessDate')

In [9]:
df

,businessDate,totalTrades,totalTradedQuantity,totalTradedValue,highPrice,lowPrice,closePrice,year,month
223,2025-08-11,343,95193,37038550.7,397.9,383.0,383.82,2025,8
222,2025-08-12,274,81542,31015101.2,385.0,377.0,380.33,2025,8
221,2025-08-13,324,117397,44894624.4,392.0,375.9,380.87,2025,8
220,2025-08-14,346,85067,32872938.3,394.7,379.1,390.47,2025,8
219,2025-08-17,222,50520,19532195.4,394.0,384.0,384.88,2025,8
...,...,...,...,...,...,...,...,...,...
4,2026-08-04,88,21045,7997141.9,388.0,378.2,383.90,2026,8
3,2026-08-05,56,9947,3769629.9,388.0,377.1,379.90,2026,8
2,2026-08-06,90,23316,8867818.6,385.0,375.5,379.00,2026,8
1,2026-08-07,53,7991,3008338.7,381.5,375.0,375.00,2026,8
0,2026-08-10,46,4858,1821167.5,379.5,373.1,374.00,2026,8

In [10]:
import pandas_ta as ta

In [32]:
df['rsi']  = ta.rsi(df['closePrice'],length=14)

In [33]:
df

,businessDate,totalTrades,totalTradedQuantity,totalTradedValue,highPrice,lowPrice,closePrice,year,month,rsi
223,2025-08-11,343,95193,37038550.7,397.9,383.0,383.82,2025,8,NaN
222,2025-08-12,274,81542,31015101.2,385.0,377.0,380.33,2025,8,0.000000
221,2025-08-13,324,117397,44894624.4,392.0,375.9,380.87,2025,8,1.176214
220,2025-08-14,346,85067,32872938.3,394.7,379.1,390.47,2025,8,19.340016
219,2025-08-17,222,50520,19532195.4,394.0,384.0,384.88,2025,8,17.341296
...,...,...,...,...,...,...,...,...,...,...
4,2026-08-04,88,21045,7997141.9,388.0,378.2,383.90,2026,8,39.844465
3,2026-08-05,56,9947,3769629.9,388.0,377.1,379.90,2026,8,36.824087
2,2026-08-06,90,23316,8867818.6,385.0,375.5,379.00,2026,8,36.159904
1,2026-08-07,53,7991,3008338.7,381.5,375.0,375.00,2026,8,33.286321
0,2026-08-10,46,4858,1821167.5,379.5,373.1,374.00,2026,8,32.589064

In [34]:
df.value_counts

<bound method DataFrame.value_counts of     businessDate  totalTrades  totalTradedQuantity  totalTradedValue  \
223   2025-08-11          343                95193        37038550.7
222   2025-08-12          274                81542        31015101.2
221   2025-08-13          324               117397        44894624.4
220   2025-08-14          346                85067        32872938.3
219   2025-08-17          222                50520        19532195.4
..           ...          ...                  ...               ...
4     2026-08-04           88                21045         7997141.9
3     2026-08-05           56                 9947         3769629.9
2     2026-08-06           90                23316         8867818.6
1     2026-08-07           53                 7991         3008338.7
0     2026-08-10           46                 4858         1821167.5

     highPrice  lowPrice  closePrice  year  month        rsi
223      397.9     383.0      383.82  2025      8        NaN
222      385.0     377.0      380.33  2025      8   0.000000
221      392.0     375.9      380.87  2025      8   1.176214
220      394.7     379.1      390.47  2025      8  19.340016
219      394.0     384.0      384.88  2025      8  17.341296
..         ...       ...         ...   ...    ...        ...
4        388.0     378.2      383.90  2026      8  39.844465
3        388.0     377.1      379.90  2026      8  36.824087
2        385.0     375.5      379.00  2026      8  36.159904
1        381.5     375.0      375.00  2026      8  33.286321
0        379.5     373.1      374.00  2026      8  32.589064

[224 rows x 10 columns]>

In [35]:
df[:223]

,businessDate,totalTrades,totalTradedQuantity,totalTradedValue,highPrice,lowPrice,closePrice,year,month,rsi
223,2025-08-11,343,95193,37038550.7,397.9,383.0,383.82,2025,8,NaN
222,2025-08-12,274,81542,31015101.2,385.0,377.0,380.33,2025,8,0.000000
221,2025-08-13,324,117397,44894624.4,392.0,375.9,380.87,2025,8,1.176214
220,2025-08-14,346,85067,32872938.3,394.7,379.1,390.47,2025,8,19.340016
219,2025-08-17,222,50520,19532195.4,394.0,384.0,384.88,2025,8,17.341296
...,...,...,...,...,...,...,...,...,...,...
5,2026-08-03,48,8276,3173106.9,389.0,380.1,384.80,2026,8,40.539172
4,2026-08-04,88,21045,7997141.9,388.0,378.2,383.90,2026,8,39.844465
3,2026-08-05,56,9947,3769629.9,388.0,377.1,379.90,2026,8,36.824087
2,2026-08-06,90,23316,8867818.6,385.0,375.5,379.00,2026,8,36.159904
1,2026-08-07,53,7991,3008338.7,381.5,375.0,375.00,2026,8,33.286321

In [36]:
type(df)

pandas.core.frame.DataFrame

In [37]:
df["rsi"].isna().sum()

np.int64(1)

In [39]:
df[["businessDate", "closePrice", "rsi"]].tail()

  businessDate  closePrice        rsi
4   2026-08-04       383.9  39.844465
3   2026-08-05       379.9  36.824087
2   2026-08-06       379.0  36.159904
1   2026-08-07       375.0  33.286321
0   2026-08-10       374.0  32.589064

In [40]:
df

,businessDate,totalTrades,totalTradedQuantity,totalTradedValue,highPrice,lowPrice,closePrice,year,month,rsi
223,2025-08-11,343,95193,37038550.7,397.9,383.0,383.82,2025,8,NaN
222,2025-08-12,274,81542,31015101.2,385.0,377.0,380.33,2025,8,0.000000
221,2025-08-13,324,117397,44894624.4,392.0,375.9,380.87,2025,8,1.176214
220,2025-08-14,346,85067,32872938.3,394.7,379.1,390.47,2025,8,19.340016
219,2025-08-17,222,50520,19532195.4,394.0,384.0,384.88,2025,8,17.341296
...,...,...,...,...,...,...,...,...,...,...
4,2026-08-04,88,21045,7997141.9,388.0,378.2,383.90,2026,8,39.844465
3,2026-08-05,56,9947,3769629.9,388.0,377.1,379.90,2026,8,36.824087
2,2026-08-06,90,23316,8867818.6,385.0,375.5,379.00,2026,8,36.159904
1,2026-08-07,53,7991,3008338.7,381.5,375.0,375.00,2026,8,33.286321
0,2026-08-10,46,4858,1821167.5,379.5,373.1,374.00,2026,8,32.589064

In [41]:
df = df.sort_values("businessDate").reset_index(drop=True)

In [42]:
df

,businessDate,totalTrades,totalTradedQuantity,totalTradedValue,highPrice,lowPrice,closePrice,year,month,rsi
0,2025-08-11,343,95193,37038550.7,397.9,383.0,383.82,2025,8,NaN
1,2025-08-12,274,81542,31015101.2,385.0,377.0,380.33,2025,8,0.000000
2,2025-08-13,324,117397,44894624.4,392.0,375.9,380.87,2025,8,1.176214
3,2025-08-14,346,85067,32872938.3,394.7,379.1,390.47,2025,8,19.340016
4,2025-08-17,222,50520,19532195.4,394.0,384.0,384.88,2025,8,17.341296
...,...,...,...,...,...,...,...,...,...,...
219,2026-08-04,88,21045,7997141.9,388.0,378.2,383.90,2026,8,39.844465
220,2026-08-05,56,9947,3769629.9,388.0,377.1,379.90,2026,8,36.824087
221,2026-08-06,90,23316,8867818.6,385.0,375.5,379.00,2026,8,36.159904
222,2026-08-07,53,7991,3008338.7,381.5,375.0,375.00,2026,8,33.286321
223,2026-08-10,46,4858,1821167.5,379.5,373.1,374.00,2026,8,32.589064

In [43]:
df["rsi"] = ta.rsi(df["closePrice"], length=14)

In [44]:
df

,businessDate,totalTrades,totalTradedQuantity,totalTradedValue,highPrice,lowPrice,closePrice,year,month,rsi
0,2025-08-11,343,95193,37038550.7,397.9,383.0,383.82,2025,8,NaN
1,2025-08-12,274,81542,31015101.2,385.0,377.0,380.33,2025,8,0.000000
2,2025-08-13,324,117397,44894624.4,392.0,375.9,380.87,2025,8,1.176214
3,2025-08-14,346,85067,32872938.3,394.7,379.1,390.47,2025,8,19.340016
4,2025-08-17,222,50520,19532195.4,394.0,384.0,384.88,2025,8,17.341296
...,...,...,...,...,...,...,...,...,...,...
219,2026-08-04,88,21045,7997141.9,388.0,378.2,383.90,2026,8,39.844465
220,2026-08-05,56,9947,3769629.9,388.0,377.1,379.90,2026,8,36.824087
221,2026-08-06,90,23316,8867818.6,385.0,375.5,379.00,2026,8,36.159904
222,2026-08-07,53,7991,3008338.7,381.5,375.0,375.00,2026,8,33.286321
223,2026-08-10,46,4858,1821167.5,379.5,373.1,374.00,2026,8,32.589064